Repository BiswadeepMazumder/InventoryManagement, pull requests merged in 2024-12, with the labels that each got.

#57 comments added for items controller
  API/Controllers/ItemController.cs
Labels: documentation

#59 Print Order Invoice
  src/app/dashboard/items/page.tsx
  src/app/dashboard/orders/page.tsx
  src/app/dashboard/suppliers/page.tsx
  src/components/item/CreateItemModal.tsx
  src/components/item/DeleteItemModal.tsx
  src/components/item/UpdateItemModal.tsx
  src/components/order/CreateOrderModal.tsx
  src/components/order/DeleteOrderModal.tsx
  src/components/order/PlaceOrderModal.tsx
  src/components/order/ViewOrderModal.tsx
  src/components/supplier/CreateSupplierModal.tsx
  src/components/supplier/DeleteSupplierModal.tsx
  src/components/supplier/UpdateSupplierModal.tsx
  src/services/order.services.ts
Labels: enhancement

#61 Fix Minor Bugs
  src/app/dashboard/account/page.tsx
  src/app/dashboard/items/page.tsx
  src/app/dashboard/orders/page.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/suppliers/page.tsx
  src/components/auth/ResetPasswordForm.tsx
  src/components/item/CreateItemModal.tsx
  src/components/item/schema.ts
  src/components/order/CreateOrderModal.tsx
  src/components/order/PlaceOrderModal.tsx
  src/components/order/schema.ts
  src/components/overview/CurrentOrders.tsx
  src/components/overview/PastOrders.tsx
  src/components/overview/UpcomingOrders.tsx
  src/components/supplier/CreateSupplierModal.tsx
  src/components/supplier/schema.ts
  src/contexts/UserContext.tsx
  src/types/user.ts
Labels: bug
